cargo_lower: {mesh: "package://object_loader/example_meshes/CargoPanelLower.stl", scale: [0.5, 0.1, 0.05]}
sidewall   : {mesh: "package://object_loader/example_meshes/SidewallPanel.stl", color: [255,0,0,1]}
scatola    : {box: [0.1, 0.1, 0.1], color: [255,255,0,1]}


cube:
  color: [1,0.8,0,1.]
  box:  [0.05,0.05,0.05]
  offset_quaternion: [ 0.5, 0.5, 0.5, 0.5 ]
  offset: [0, 0, 0]




